const CATEGORIES = [
  { name: 'LUTs & Color', slug: 'luts-color' },
  { name: 'Transitions', slug: 'transitions' },
  { name: 'Sound FX & Music', slug: 'sound-fx-music' },
  { name: 'Templates & Titles', slug: 'templates-titles' },
  { name: 'Plugins', slug: 'plugins' },
  { name: 'Overlays', slug: 'overlays' },
];

// category referenced by name; resolved to category_id at seed time
const PRODUCTS = [
  { id: 'analog-warmth-luts', name: 'Analog Warmth LUT Pack', category: 'LUTs & Color', price: 39,
    software: ['Premiere Pro', 'DaVinci Resolve', 'Final Cut Pro'], formats: '.cube, .3dl', file_count: '24 LUTs',
    resolution: 'Any resolution', license: 'Personal & Commercial', ref: 'CL-LUT-024',
    color_from: '#FF7A3D', color_to: '#7A3115', icon: 'color',
    description: 'A set of 24 film-inspired LUTs built around warm highlights and lifted shadows — the kind of grade that makes digital footage feel shot on stock.' },
  { id: 'kinetic-cuts-transitions', name: 'Kinetic Cuts Transitions', category: 'Transitions', price: 49,
    software: ['Premiere Pro', 'After Effects'], formats: '.mogrt, .aep', file_count: '40 transitions',
    resolution: '4K', license: 'Personal & Commercial', ref: 'CL-TRN-040',
    color_from: '#8B7FD8', color_to: '#332966', icon: 'transition',
    description: 'Forty snap-cut and whip transitions built for fast-paced edits — drag, drop, and match to the beat.' },
  { id: 'whoosh-impact-sfx', name: 'Whoosh & Impact SFX Library', category: 'Sound FX & Music', price: 29,
    software: ['Universal'], formats: '.wav, 48kHz', file_count: '180 sounds',
    resolution: '—', license: 'Personal & Commercial', ref: 'CL-SFX-180',
    color_from: '#2FB6A9', color_to: '#0F433D', icon: 'wave',
    description: '180 hand-layered whooshes, impacts and risers for transitions, titles and reveals.' },
  { id: 'broadcast-titles-mogrt', name: 'Broadcast Titles Pack', category: 'Templates & Titles', price: 59,
    software: ['Premiere Pro'], formats: '.mogrt', file_count: '32 templates',
    resolution: '4K', license: 'Personal & Commercial', ref: 'CL-TPL-032',
    color_from: '#FF7A3D', color_to: '#B8451E', icon: 'layers',
    description: 'Lower thirds, full-screen titles and credit rolls styled for news and documentary work, fully editable in Essential Graphics.' },
  { id: 'neon-glitch-transitions', name: 'Neon Glitch Transitions', category: 'Transitions', price: 45,
    software: ['After Effects', 'Premiere Pro'], formats: '.aep, .mogrt', file_count: '25 transitions',
    resolution: '4K', license: 'Personal & Commercial', ref: 'CL-TRN-025',
    color_from: '#E4574C', color_to: '#5C1712', icon: 'transition',
    description: 'RGB-split glitch and digital distortion transitions for music videos, gaming content and tech reviews.' },
  { id: 'optical-flares-plugin', name: 'Optical Flares Toolkit', category: 'Plugins', price: 89,
    software: ['After Effects'], formats: '.aex plugin', file_count: '1 plugin, 60 presets',
    resolution: 'Any resolution', license: 'Single-seat license', ref: 'CL-PLG-001',
    color_from: '#8B7FD8', color_to: '#2B2450', icon: 'plug',
    description: 'A native After Effects plugin for physically-based lens flares, with 60 presets covering anamorphic, vintage and J.J.-style rigs.' },
  { id: 'teal-orange-luts', name: 'Cinematic Teal & Orange LUTs', category: 'LUTs & Color', price: 35,
    software: ['DaVinci Resolve', 'Premiere Pro'], formats: '.cube', file_count: '18 LUTs',
    resolution: 'Any resolution', license: 'Personal & Commercial', ref: 'CL-LUT-018',
    color_from: '#2FB6A9', color_to: '#FF7A3D', icon: 'color',
    description: 'The classic blockbuster grade — cool shadows, warm skin tones — tuned in 18 strengths from subtle to full push.' },
  { id: 'podcast-waveform-overlays', name: 'Podcast Waveform Overlays', category: 'Templates & Titles', price: 25,
    software: ['Universal'], formats: '.mp4 alpha, .mogrt', file_count: '15 overlays',
    resolution: '4K, alpha channel', license: 'Personal & Commercial', ref: 'CL-TPL-015',
    color_from: '#2FB6A9', color_to: '#0F3B36', icon: 'wave',
    description: 'Animated waveform bars and caption-ready lower thirds built specifically for podcast and interview cuts.' },
  { id: 'smooth-zoom-transitions', name: 'Smooth Zoom Transitions', category: 'Transitions', price: 19,
    software: ['CapCut', 'Premiere Pro'], formats: '.mp4 alpha, template', file_count: '20 transitions',
    resolution: '1080p / 4K', license: 'Personal & Commercial', ref: 'CL-TRN-020',
    color_from: '#B7D66B', color_to: '#4B5A22', icon: 'transition',
    description: 'Snappy zoom-punch transitions built for short-form vertical content — the exact move you see on every travel reel.' },
  { id: 'ambient-beds-music', name: 'Ambient Beds Music Pack', category: 'Sound FX & Music', price: 59,
    software: ['Universal'], formats: '.wav, .mp3', file_count: '22 tracks',
    resolution: '—', license: 'Personal & Commercial', ref: 'CL-MUS-022',
    color_from: '#2FB6A9', color_to: '#1B4B45', icon: 'wave',
    description: 'Twenty-two royalty-free ambient beds for voiceover, documentary and corporate work — loopable, stem-split, no clearance needed.' },
  { id: 'split-screen-toolkit', name: 'Split Screen Toolkit', category: 'Templates & Titles', price: 69,
    software: ['Premiere Pro', 'After Effects'], formats: '.mogrt, .aep', file_count: '28 layouts',
    resolution: '4K', license: 'Personal & Commercial', ref: 'CL-TPL-028',
    color_from: '#FF7A3D', color_to: '#8B7FD8', icon: 'layers',
    description: 'Twenty-eight responsive split-screen and grid layouts for reaction content, comparisons and multi-cam interviews.' },
  { id: 'film-grain-halation', name: 'Film Grain & Halation Overlays', category: 'Overlays', price: 32,
    software: ['Universal'], formats: '.mp4 alpha, .mov', file_count: '16 overlays',
    resolution: '4K', license: 'Personal & Commercial', ref: 'CL-OVL-016',
    color_from: '#E4574C', color_to: '#3A1512', icon: 'grain',
    description: 'Scanned 16mm and 35mm grain plates plus halation blooms to knock the digital edge off any grade.' },
];

const TUTORIALS = [
  { id: 'premiere-for-beginners', title: 'Premiere Pro for Beginners', software: 'Premiere Pro', level: 'Beginner', topic: 'Editing Fundamentals',
    instructor: 'Maya Chen', role: 'Senior Editor, 10+ yrs broadcast',
    summary: 'Start from a blank project and finish with a fully cut, exported sequence — timeline basics, trimming, transitions and export settings explained without jargon.',
    lessons: [
      ['Setting up your first project', 380], ['Importing and organizing media', 340],
      ['Timeline basics: tracks, clips, playhead', 490], ['Trimming with ripple & roll tools', 570],
      ['Cross dissolves and adding titles', 435], ['Audio levels and keyframes', 480],
      ['Exporting with Media Encoder', 365],
    ]},
  { id: 'lumetri-color-grading', title: 'Color Grading with Lumetri', software: 'Premiere Pro', level: 'Intermediate', topic: 'Color Grading',
    instructor: 'Jonas Riker', role: 'Freelance Colorist',
    summary: 'A practical pass through the Lumetri panel — reading scopes, building a look from scratch, and matching shots across a scene.',
    lessons: [
      ['Understanding scopes: waveform & vectorscope', 560], ['White balance and primary correction', 520],
      ['Building a look with creative wheels', 605], ['Secondary grading with the HSL qualifier', 690],
      ['Matching shots across a scene', 590], ['Exporting a custom LUT', 375],
    ]},
  { id: 'ae-motion-graphics-bootcamp', title: 'After Effects Motion Graphics Bootcamp', software: 'After Effects', level: 'Intermediate', topic: 'Motion Graphics',
    instructor: 'Priya Nandan', role: 'Motion Designer',
    summary: 'The core motion-design toolkit — keyframes, shape layers, parenting and type animation — building up to a finished lower-third package.',
    lessons: [
      ['Interface tour & composition setup', 430], ['Keyframes and the graph editor', 680],
      ['Shape layers and path animation', 640], ['Null objects and parenting', 535],
      ['Text animation presets & custom type', 570], ['Building a lower-third from scratch', 735],
      ['Rendering and delivery settings', 390], ['Keeping a scalable project structure', 465],
    ]},
  { id: 'resolve-color-mastery', title: 'DaVinci Resolve Color Mastery', software: 'DaVinci Resolve', level: 'Advanced', topic: 'Color Grading',
    instructor: 'Elena Torres', role: 'Colorist, feature & commercial',
    summary: 'Node-based grading from the ground up — building complex trees, tracking power windows, and delivering a consistent look across cameras.',
    lessons: [
      ['Node trees: serial, parallel, layer', 610], ['Camera-native log workflows', 720],
      ['Power windows and tracking', 795], ['Building a teal & orange grade', 880],
      ['Match grading across cameras', 680], ['Delivering with color management', 545],
    ]},
  { id: 'fcp-speed-editing', title: 'Final Cut Pro Speed Editing', software: 'Final Cut Pro', level: 'Beginner', topic: 'Workflow & Shortcuts',
    instructor: 'Devon Marsh', role: 'YouTube Editor',
    summary: 'The magnetic timeline, keyword collections and keyboard-only trimming — a lean workflow built for turning around videos fast.',
    lessons: [
      ['The magnetic timeline explained', 410], ['Keyword collections & smart search', 440],
      ['Trimming without leaving the keyboard', 490], ['Compound clips & multicam basics', 540],
      ['Fast exports with Compressor', 340],
    ]},
  { id: 'capcut-social-content', title: 'CapCut for Social Content', software: 'CapCut', level: 'Beginner', topic: 'Editing Fundamentals',
    instructor: 'Ana Reyes', role: 'Content Creator, 400K+ following',
    summary: 'Everything for a vertical-first workflow — auto captions, trending effects and exporting cleanly for every platform.',
    lessons: [
      ['Vertical timeline basics', 310], ['Auto captions & text styles', 380],
      ['Trending transitions & effects', 425], ['Keyframing zoom & pan on mobile', 405],
      ['Exporting for Reels, TikTok & Shorts', 290],
    ]},
  { id: 'sound-design-mixing', title: 'Sound Design & Mixing Essentials', software: 'Premiere Pro', level: 'Intermediate', topic: 'Audio Mixing',
    instructor: 'Owen Baptiste', role: 'Sound Designer',
    summary: 'Get dialogue, music and effects sitting together properly — EQ, compression and mixing to a broadcast-safe loudness target.',
    lessons: [
      ['Audio track setup & submixes', 450], ['EQ and de-essing dialogue', 555],
      ['Compression basics for voiceover', 520], ['Building an ambience bed', 475],
      ['Mixing to loudness standards', 620],
    ]},
  { id: 'advanced-keyframing-expressions', title: 'Advanced Keyframing & Expressions', software: 'After Effects', level: 'Advanced', topic: 'Visual Effects',
    instructor: 'Priya Nandan', role: 'Motion Designer',
    summary: 'Move past manual keyframing — wiggle, loopOut, and pickwhip your way to rigs that animate themselves.',
    lessons: [
      ['Expression basics: wiggle & time', 550], ['Linking properties with the pickwhip', 460],
      ['loopOut() and procedural animation', 630], ['Building a reusable expression rig', 770],
      ['Debugging and optimizing expressions', 495],
    ]},
  { id: 'fusion-vfx-resolve', title: 'Fusion Visual Effects in Resolve', software: 'DaVinci Resolve', level: 'Advanced', topic: 'Visual Effects',
    instructor: 'Marcus Ilya', role: 'VFX Artist',
    summary: 'Cross over into the Fusion page for node-based compositing — rotoscoping, tracking, and a simple screen replacement from start to finish.',
    lessons: [
      ['Fusion page interface & node basics', 530], ['Rotoscoping with the polygon tool', 700],
      ['Planar tracking with the tracker node', 620], ['Compositing a screen replacement', 790],
      ['Rendering Fusion comps back to Edit', 405],
    ]},
];

const ADMIN_CREDENTIALS = [
  { username: 'admin', email: 'admin@cutlab.com', password: 'admin123', role: 'admin' },
];

module.exports = { CATEGORIES, PRODUCTS, TUTORIALS, ADMIN_CREDENTIALS };


